channels:
  - conda-forge
dependencies:
  - Flask=1.1.2
  - numpy
  - orjson
  - pandas
  - pillow=7.1.0
  - requests
  - scikit-learn=0.20.2
  - scikit-image=0.14.2
  - scipy
  - tifffile=2020.10.1
  - waitress
  - zarr
  - pip
  - pip:
      - opencv-python==4.4.0.*


