channels:
  - conda-forge
dependencies:
  - Flask=1.1.2
  - numpy
  - pandas
  - pillow=7.0.0
  - requests
  - scikit-learn
  - scikit-image=0.14.2
  - scipy
  - tifffile
  - umap-learn=0.4.6
  - pip
  - pip:
      - pyvips==2.1.8
      - opencv-python==4.2.0.*
      - orjson==3.3.0
      - napari[pyqt5]
      - scimap==0.1.11
