name: dockerhub

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Clean up the release tag test
        id: cleantag
        run: |
          tag=$(echo ${{ steps.branch_name.outputs.SOURCE_TAG }} | tr -d v)
          echo "::set-output name=tag::${{ github.repository }}:${tag%"_gating"}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{steps.cleantag.outputs.tag}}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
